app_name: "task-agent"

inference:
  max_concurrent_tasks: 5
  timeout_seconds: 60
  task_retention_hours: 24  # 保留已完成任务24小时
  max_tasks_count: 1000     # 最多保存1000个任务

logging:
  level: "INFO"              # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: false        # 是否启用文件日志
  file_path: "logs/app.log"  # 文件日志路径

DEV_MODE: true